@startuml
'title Diagrama de Componentes: Estructura CRISP-DM para Dátil Medjool

'left to right direction

!theme mono

package "CRISP-DM adaptado" {
  [1. Comprensión del negocio]
  [2. Comprensión de los datos]
  [3. Preparación de los datos]
  [4. Modelado]
  [5. Evaluación]
  [6. Prototipado]
}

[1. Comprensión del negocio] -d-> [2. Comprensión de los datos]
[2. Comprensión de los datos] -d-> [3. Preparación de los datos]
[3. Preparación de los datos] -r-> [4. Modelado]
[4. Modelado] -u-> [5. Evaluación]
[5. Evaluación] -u-> [6. Prototipado]

' Loopbacks típicos de CRISP-DM
[5. Evaluación] --> [3. Preparación de los datos] : Ajustes
[5. Evaluación] --> [4. Modelado] : Reentrenamiento
[6. Prototipado] -l-> [1. Comprensión del negocio] : Retroalimentación
@enduml
